### ISSUE TITLE
penalty tune() values

### ISSUE THREAD

**Issue by fkgruber** [tidymodels/tune#177]
Hi
It appears that when we try to optimize a parameter like penalty if we don't specify the grid it uses some default value. However, certain engines like glmnet provide a more appropriate range for the penalty based on the specific training data. 

It would be helpful in tune() would use the recommended range by the engine if available.

FKG

**Comment by topepo** [comment]
The range depends on the value of the mixture so you would have to fit multiple models to get a range (that's why we use a fairly large range as-is). 

If you do that, you're doing a non-trivial fraction of the work of model tuning. It's more efficient to use the default and then tune again within a range that you think is appropriate based on the initial results. 

Alternatively, you can use `tune_bayes()` and let it make the determination.
