### ISSUE TITLE
How to collect the metrics for the analysis datasets?

### ISSUE THREAD

**Issue by kbzsl** [tidymodels/tune#215]
Looking through the documentation, it looks that it not possible to collect easily the metrics for the analysis datasets (cross-validation) after `fit_resamples()`. The `collect_metrics()` is extracting the metrics for the assessment datasets.

Is it feasible to add an `extract_fit()`? Something similar to `extract_model()` or `extract_recipe()`.

**Comment by topepo** [comment]
We don't directly support re-predicting the analysis or training sets (since we discourage doing this).

There are existing functions to [extract the model fit and recipe](https://tune.tidymodels.org/reference/extract_recipe.html). Take a look at the documentation for the [`tune_*`](https://tune.tidymodels.org/reference/tune_grid.html#extracting-information) functions or `fit_resamples()`.
