### ISSUE TITLE
metrics with a target value of zero

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#243]
`show_best()` and others have code that looks like: 

```r
  if (maximize) {
    summary_res <- summary_res %>% dplyr::arrange(dplyr::desc(mean))
  } else {
    summary_res <- summary_res %>% dplyr::arrange(mean)
  }
```

This should be adjusted for cases when there is a target value. 

Perhaps we can use `maximize = FALSE` and arrange by `(abs(mean - target))`. 

@DavisVaughan

**Comment by DavisVaughan** [comment]
Currently all yardstick metrics optimize with one of maximize/minimize/zero. I havent run across any that have an arbitrary `target`, but I guess it is possible.

It might be worth leaving the `direction` variable as a character string, rather than converting it to a logical `maximize` variable. Then you'd just handle the 3 cases by expanding the if statement you have above.

If we run into metrics later on that have some arbitrary target value, then we'd have to reconsider how this works in both yardstick and tune (currently in yardstick `direction` is a character string, but it would probably have to become a numeric value for arbitrary targets)
