### ISSUE TITLE
Error: Leave-one-out cross-validation is not currently supported with tune

### ISSUE THREAD

**Issue by albert-ying** [tidymodels/tune#365]
Hi, when I was using `loo_cv` for tuning, it gives me an error
```
data_cv = loo_cv(data_train)

tune_res = tune_grid(
    data_wf,
    grid = model_grid,
    resample = data_cv,
    metrics = model_metrics
  )
```
```
Error: Leave-one-out cross-validation is not currently supported with tune.
```

I'm currently using a workaround by doing.
```
data_cv = vfold_cv(data_train, v = nrow(data_train))
```

Will this give me the same result as leave-one-out cv? And why loocv is not supported for tuning?

Thank you!

**Comment by juliasilge** [comment]
You can read a bit about why leave-one-out methods are not fully integrated into tidymodels infrastructure like our tuning functions [here](https://www.tmwr.org/resampling.html#leave-one-out-cross-validation).

**Comment by topepo** [comment]
From a statistical standpoint, it is a pretty sub-optimal method of resampling. 

From a software standpoint, the code complexity would greatly increase since the nature of the results are so different (e.g. there is one estimate returned for `n` resamples). Basically, the benefit:cost ratio is too small to include.
