### ISSUE TITLE
tune_bayes() frozen

### ISSUE THREAD

**Issue by siegfried** [tidymodels/tune#423]
Bayesian tuning is often frozen at `Gaussian process model` when there are more than 80 iterations. I cannot think of a good way to reproduce it for now. I was tuning XGBoost models with R 4.1.0 on macOS 12.0.1; the model was trained in 6 threads but no parallel process is used.

**Comment by juliasilge** [comment]
Are you able to create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this with a certain dataset if you [bump up `iter` to greater than 80](https://tune.tidymodels.org/reference/tune_bayes.html)? When I tried this with some example datasets, I did not see a problem and the function completed tuning.

I know it can be frustrating to create a reprex for a complex situation, but the goal of a reprex is to make it possible for us to recreate your problem so that we can understand it and/or fix it. We really are just flailing in the dark without that. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌
