### ISSUE TITLE
Cran Checks (Modeltime): 

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/tune#471]
Hey guys, 
I'm getting a weird error in[ Modeltime's CRAN Check](https://cran.r-project.org/web/checks/check_results_modeltime.html)

``` r
Error in UseMethod("tune_args") :
     no applicable method for 'tune_args' applied to an object of class "c('boost_tree', 'model_spec')"
    Calls: <Anonymous> ... obj_sum.default -> type_sum -> type_sum.model_spec -> <Anonymous>
    Execution halted 
```

Do you know what this is related to and if I need to do something to fix?

-Matt

**Comment by juliasilge** [comment]
There _is_ a new version of parsnip on CRAN and I believe that the changes to how `tune_args()` is registered are the problem here. Before we reexported `tune_args()` from generics, but [now we lazily register the method](https://github.com/tidymodels/parsnip/commit/52ca9d0bd15f1dffacc87acdb2b60326f67d649c) depending on the tune version. @topepo is working on a tune release right now; is there anything else that Matt should/can do here other than wait for the tune release?

**Comment by mdancho84** [comment]
If that fix is coming and it will take care of it, I can probably just let CRAN know to avoid getting modeltime kicked off. But just let me know.

**Comment by topepo** [comment]
No, I'm trying to send it in today or tomorrow.

**Comment by topepo** [comment]
@mdancho84 our new versions _should_ solve your issues. However, CRAN might want you to send in a new version with updated package dependency versions. 

Also, Davis will probably send workflows in today or tomorrow (if there are issues with that too).

**Comment by mdancho84** [comment]
Awesome guys. I will stay tuned. 😅

Sorry for my really bad pun.

**Comment by simonpcouch** [comment]
Going to go ahead and close as resolved—feel free to holler if this issue persists!
