### ISSUE TITLE
Suggestion: tuning whether to include specific steps or not.

### ISSUE THREAD

**Issue by ymer** [tidymodels/tune#57]
For example, the step_* recipe methods could have a "use_[stepname]" attribute. If this one is set to tune(), the tuning is performed both with and without that step.

**Comment by topepo** [comment]
This has been discussed some over in the recipes repo. The current thinking is to handle this on a step-by-step basis since removing a particular step could be catastrophic for the overall recipe. Plus, if there was an off/on parameter, then that value wouldn't line up with any tuning parameters in that step. 

As an example, there is the ability to ask for zero components with some of the dimension reduction tools (like `step_pca`). That's a good example since any down-stream steps that select on `starts_with("pca_")` would fail.  Also, when plotting the effect of the parameter, `num_terms = 0` would line up nicely in the plot. 

Are there particular steps that you are interested in?

**Comment by ymer** [comment]
I think transformations like normalization, step_log. Hmm it would also be nice to have the type of imputation steps tuned, but that wouldn't work in the framework I suggested.

**Comment by EmilHvitfeldt** [comment]
It would be possible to create as general imputation step such that you could vary the type of imputation. The creation of such a step might take a little thought as each imputation method have their own possible tune-able arguments.

**Comment by topepo** [comment]
To that point, I think that a unified approach to tuning different _types_ of techniques (including using no technique) might sound like a good idea but would be a mess programmatically and logically (and the user api would be bananas). 

It isn't great to have a set of `tune` results with different parameters/methods but I think it would be better than a single `tune` result.

**Comment by topepo** [comment]
I think that this is now best handled by the [workflows package](http://workflowsets.tidymodels.org/).
