### ISSUE TITLE
Tune Aggregation Function?

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/tune#75]
In [this issue](https://github.com/tidymodels/textrecipes/issues/20#issuecomment-449875002) in textrecipes, @kanishkamisra pointed out that the aggregation function used for word embeddings can have a big impact on the model (see also [the paper he mentioned](https://arxiv.org/abs/1607.00570)). Would it (conceptually) make sense to make the "aggregation" argument in this new step tunable? I can definitely imagine wanting to tune this, but I'm not sure if that fits within {tune}, or should be handled more manually as a special case.

**Comment by topepo** [comment]
I'll need to think about this a bit more but.. 

I think that I would add an option with a set of pre-defined aggregation options (e.g. "mean", "max", and so on instead of functions `mean()`, `max()`, etc). I would let users choose one of them and prefix new features with that option. If they want multiples, they can call the step again. This seems like a pretty fast operation, so that wouldn't be a big deal. 

To facilitate tuning, we'd want to enable people to tune over this parameter and maybe that should also include some signal of "don't do this step". To that end, I would suggest that,  _if_ the number of embedding dimensions is a tuning parameter (20 in your example), maybe allow a value of zero to mean that no new features are created. Otherwise, I'd have to think more about this.

**Comment by jonthegeek** [comment]
The pre-trained embeddings have some number of dimensions (25, 50, 100, 200, or 300 for GloVe, depending which pre-training you use), so I didn't intend to let the user choose how many of them to use; maybe WHICH ones of them would be a tunable parameter, though; I'll have to think about that.

One problem with adding the step multiple times is that, for reproducibility, I intend to include the full tibble of pre-trained embeddings in the prepped recipe. I'll have to think about whether I can make sure R doesn't copy that object repeatedly if the step is included multiple times. The largest GloVe embeddings are something like 4gb, for example, so throwing a few of those into the recipe wouldn't be very viable.

Definitely a lot to think about. I think I can get a v1 working without nailing all of this down, but I wanted to put it out there. 

I imagine #57 might relate to this, depending how we code this.
