### ISSUE TITLE
Control recipe and model separately in tune?

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/tune#83]
I have a recipe that uses the java version of Stanford's CoreNLP. In theory I could make it work, but right now it chokes when I try to tune, because the engine isn't available to the subprocesses, I think.

Maybe my case is relatively unique, but might it be possible to specify what can be parallelized separately in `grid_control`? It'd definitely be nice for the majority of the grid search to be parallel, with just the recipe baking un-parallelized.

**Comment by topepo** [comment]
It would be helpful to know how you were parallel processing. 

(in reverse order)

> Maybe my case is relatively unique, but might it be possible to specify what can be parallelized separately in `grid_control`? It'd definitely be nice for the majority of the grid search to be parallel, with just the recipe baking un-parallelized.

That would be pretty difficult to do and might eliminate the advantages of parallel processing. 

> I have a recipe that uses the java version of Stanford's CoreNLP. In theory I could make it work, but right now it chokes when I try to tune, because the engine isn't available to the subprocesses, I think.

The underlying issue is that different parallel processing techniques expose variables and package differently. `foreach` is excellent but it does not always access things that you need in the workers (see [here](https://github.com/topepo/caret/issues/1017) for more info).

For `recipes`, we need to be able to contain the required packages as data in the step objects (sort of like how `parsnip` does). I'm working on that now. 

In the meantime, take a look at the `pkgs` option in the control functions. This will coerce the loading of the namespace. Let us know if that helps.

**Comment by jonthegeek** [comment]
Ah, it could definitely be the way I was trying to do it. This is an area that I need to get more familiar with, for sure. I was just doing:

```
library(doParallel)
cl <- makePSOCKcluster(parallel::detectCores() - 1)
registerDoParallel(cl)

{do the things}

stopCluster(cl)
```

I'll dig in a bit more and see if I can make this work. It'd definitely make my life easier if so!

**Comment by topepo** [comment]
Also, many java-based R computations like RWeka don’t play well with any parallel processing tool in R.

**Comment by jonthegeek** [comment]
So far that seems to be my case. I'm working on removing the need for this thing, and the latest version of cleanNLP uses a python backend instead of java anyway, so this might solve itself as I solve other things... but it was aggravating that that one step stopped me from speeding up all the other steps.
